#!/bin/bash
# -*- coding: utf-8 -*-
MAKE=make
MAKEFILE=Makefile.clang
# Bash on Windows (Ubuntu 16.04 Xenial) 環境の場合は http://apt.llvm.org/ を参考に clang++-4.0 を導入する。
COMPILER=clang++-4.0
BUILDDIR=../build/linux-clang-lto/2017Early
EDITION=YANEURAOU_2017_EARLY_ENGINE
TARGET=YaneuraOu-2017-early

mkdir -p ${BUILDDIR}

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse42-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 tournament-sse42-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-tournament-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-tournament-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 evallearn-sse42-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-evallearn-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-evallearn-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 tournament-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-tournament-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-tournament-avx2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 avx2-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-avx2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse41-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse41.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse41

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse2-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 evallearn-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-evallearn-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-evallearn-avx2

# export Path=C:/msys64/mingw32/bin;$PATH
# ${MAKE} -f ${MAKEFILE} clean
# ${MAKE} -f ${MAKEFILE} -j8 nosse-lto YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-nosse.log
# cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-nosse

${MAKE} -f ${MAKEFILE} clean
