#!/bin/bash
# -*- coding: utf-8 -*-
MAKE=make
MAKEFILE=Makefile
COMPILER=g++
BUILDDIR=../build/linux/2017Early
EDITION=YANEURAOU_2017_EARLY_ENGINE
TARGET=YaneuraOu-2017-early-gcc
JOBS=`grep -c ^processor /proc/cpuinfo 2>/dev/null`
declare -A TGTAIL=([bookutil-sse42]=-bookutil-sse42 [bookutil]=-bookutil-avx2 [avx2]=-avx2 [evallearn]=-evallearn-avx2 [tournament]=-tournament-avx2 [sse42]=-sse42 [evallearn-sse42]=-evallearn-sse42 [tournament-sse42]=-tournament-sse42 [sse41]=-sse41 [sse2]=-sse2)

mkdir -p ${BUILDDIR}

for key in ${!TGTAIL[*]}
do
	${MAKE} -f ${MAKEFILE} clean
	${MAKE} -f ${MAKEFILE} -j${JOBS} ${key} YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee $BUILDDIR/${TARGET}${TGTAIL[$key]}.log
	cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}${TGTAIL[$key]}
done

${MAKE} -f ${MAKEFILE} clean
