#!/bin/bash
# -*- coding: utf-8 -*-
MAKE=make
MAKEFILE=Makefile.clang
COMPILER=clang++
BUILDDIR=../build/linux-clang/2017Early
EDITION=YANEURAOU_2017_EARLY_ENGINE
TARGET=YaneuraOu-2017-early

mkdir -p ${BUILDDIR}

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse42 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 tournament-sse42 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-tournament-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-tournament-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 evallearn-sse42 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-evallearn-sse42.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-evallearn-sse42

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 tournament YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-tournament-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-tournament-avx2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 avx2 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-avx2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse41 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse41.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse41

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 sse2 YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-sse2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-sse2

${MAKE} -f ${MAKEFILE} clean
${MAKE} -f ${MAKEFILE} -j8 evallearn YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-evallearn-avx2.log
cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-evallearn-avx2

# export Path=C:/msys64/mingw32/bin;$PATH
# ${MAKE} -f ${MAKEFILE} clean
# ${MAKE} -f ${MAKEFILE} -j8 nosse YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee ${BUILDDIR}/${TARGET}-nosse.log
# cp YaneuraOu-by-gcc ${BUILDDIR}/${TARGET}-nosse

${MAKE} -f ${MAKEFILE} clean
