#!/bin/bash
# -*- coding: utf-8 -*-
mkdir -p ../build/linux/2017Early

make clean
make -j8 sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-sse42

make clean
make -j8 tournament-sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-tournament-sse42

make clean
make -j8 evallearn-sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-evallearn-sse42

make clean
make -j8 tournament YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-tournament-avx2

make clean
make -j8 avx2 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-avx2

make clean
make -j8 sse41 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-sse41

make clean
make -j8 sse2 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-sse2

make clean
make -j8 evallearn YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-evallearn-avx2

# export Path=C:/msys64/mingw32/bin;$PATH
# make clean
# make -j8 nosse YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
# cp YaneuraOu-by-gcc ../build/linux/2017Early/YaneuraOu-2017-early-nosse

make clean
