#!/usr/bin/bash
# -*- coding: utf-8 -*-
MAKE=mingw32-make
MAKEFILE=Makefile
COMPILER=clang++
BUILDDIR=../build/msys2/2017Early
EDITION=YANEURAOU_2017_EARLY_ENGINE
TARGET=YaneuraOu-2017-early-clang
declare -A TGTAIL=([sse42]=-sse42)

mkdir -p ${BUILDDIR}

for key in ${!TGTAIL[*]}
do
	${MAKE} -f ${MAKEFILE} clean
	${MAKE} -f ${MAKEFILE} -j8 ${key} YANEURAOU_EDITION=${EDITION} COMPILER=${COMPILER} 2>&1 | tee $BUILDDIR/${TARGET}${TGTAIL[$key]}.log
	cp YaneuraOu-by-gcc.exe ${BUILDDIR}/${TARGET}${TGTAIL[$key]}.exe
done

${MAKE} -f ${MAKEFILE} clean
