#!/usr/bin/bash
# -*- coding: utf-8 -*-
mkdir -p ../build/msys2/2017Early

mingw32-make clean
mingw32-make -j8 sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-sse42.exe

mingw32-make clean
mingw32-make -j8 tournament-sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-tournament-sse42.exe

mingw32-make clean
mingw32-make -j8 evallearn-sse42 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-evallearn-sse42.exe

mingw32-make clean
mingw32-make -j8 tournament YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-tournament-avx2.exe

mingw32-make clean
mingw32-make -j8 avx2 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-avx2.exe

mingw32-make clean
mingw32-make -j8 sse41 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-sse41.exe

mingw32-make clean
mingw32-make -j8 sse2 YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-sse2.exe

mingw32-make clean
mingw32-make -j8 evallearn YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-evallearn-avx2.exe

# export Path=C:/msys64/mingw32/bin;$PATH
# mingw32-make clean
# mingw32-make -j8 nosse YANEURAOU_EDITION=YANEURAOU_2017_EARLY_ENGINE
# cp YaneuraOu-by-gcc.exe ../build/msys2/2017Early/YaneuraOu-2017-early-nosse.exe

mingw32-make clean
