# deep-learning windows build
name: Make CI (DeepLearning for Windows)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    # ubuntu-latest = windows-2019
    # https://docs.github.com/ja/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
    runs-on: windows-latest

    steps:
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - uses: microsoft/setup-msbuild@v1

      - name: Checkout own repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install pkg
        run: nuget.exe restore YaneuraOu.sln
        working-directory: main

      - name: make
        run: MSBuild.exe /t:build /p:Configuration=Release-Deep /p:Platform=x64
        working-directory: main

      - name: remove libopenblas.dll
        run: rm ./main/build/Deep/libopenblas.dll -ErrorAction Continue

      - uses: actions/upload-artifact@v2
        with:
          name: build-deep-windows
          path: ./main/build/**/*
