name: NDK CI

on:
  push:
    branches:
      - master
      - 'dev/**'
      - 'develop/**'
      - 'pr_*'
  pull_request:
    branches:
      - master
      - 'dev/**'
      - 'develop/**'
      - 'pr_*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21d
    - name: ndk-build
      run: cd script && ./android_build.sh
